### ISSUE TITLE
测试图片输出结果出错

### ISSUE THREAD

**Issue by liujinlong111** [shangqigao/BayeSR#1]
请问一下我用RealworldSISR的权重测试图片，出来的效果是这样的，是需要调整什么参数么

![1](https://user-images.githubusercontent.com/62495948/232209492-0812abea-2234-44c2-bcd1-c9246f09fa8e.png)

**Comment by liujinlong111** [comment]
问题好像是内存不足，请问作者测试的时候使用的什么配置
Traceback (most recent call last):
  File "/root/miniconda3/envs/BayeSR/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/root/miniconda3/envs/BayeSR/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/root/miniconda3/envs/BayeSR/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[3,64,3136,1760] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[Node: SmSpNet/Generator/conv1/Conv2D = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](SmSpNet/Generator/conv0/Conv2D, SmSpNet/Generator/conv1/kernel/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Comment by iChenning** [comment]
我测试的图片和你的一样，请问你解决问题了吗？
